package tests

import (
	"testing"

	"go.dw1.io/rapidhash"
)

// TestRapidhashGoldenVectors asserts that the referenced rapidhash package
// produces bit-identical output to the canonical C implementation
// (c-cy/lib/rapidhash.h), which is the consensus reference for Cy topic
// hashing. Topic subject-ID assignment depends on these exact 64-bit values
// matching across nodes, so any divergence breaks interop with C nodes.
//
// Every vector was generated by compiling c-cy/lib/rapidhash.h and invoking
// rapidhash / rapidhash_withSeed on the exact input bytes below.
func TestRapidhashGoldenVectors(t *testing.T) {
	type vector struct {
		label string
		data  string
		seed  uint64
		want  uint64
	}

	// alpha mirrors the C generator's repeated input for the synthetic cases.
	alpha := []byte("abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ")
	repeat := func(n int) string {
		b := make([]byte, n)
		for i := range b {
			b[i] = alpha[i%len(alpha)]
		}
		return string(b)
	}

	vectors := []vector{
		{"empty", "", 0x0000000000000000, 0x0338dc4be2cecdae},
		{"empty_seed1", "", 0x0000000000000001, 0xad700ecdf353d5ca},
		{"byte_0x00", string([]byte{0x00}), 0x0000000000000000, 0x4f23c791b16eba02},
		{"byte_0x01", string([]byte{0x01}), 0x0000000000000000, 0xdc3697f74433a2f0},
		{"byte_0x02", string([]byte{0x02}), 0x0000000000000000, 0x573f4be1049dcfe0},
		{"byte_0x03", string([]byte{0x03}), 0x0000000000000000, 0xc6939e8fb00709ff},
		{"byte_0x04", string([]byte{0x04}), 0x0000000000000000, 0x0de2fc54831e26b2},
		{"byte_0x05", string([]byte{0x05}), 0x0000000000000000, 0x09221f212c2f3790},
		{"byte_0x06", string([]byte{0x06}), 0x0000000000000000, 0xf46415187e631f61},
		{"byte_0x07", string([]byte{0x07}), 0x0000000000000000, 0x5c2caf7d68f06d3e},
		{"byte_0x08", string([]byte{0x08}), 0x0000000000000000, 0x2db707144f7fcbfc},
		{"byte_0x09", string([]byte{0x09}), 0x0000000000000000, 0x7b51098474e06be3},
		{"byte_0x0a", string([]byte{0x0a}), 0x0000000000000000, 0x3bce942a40c8c5db},
		{"byte_0x0b", string([]byte{0x0b}), 0x0000000000000000, 0x1b8b997858cd243a},
		{"byte_0x0c", string([]byte{0x0c}), 0x0000000000000000, 0x4d31df9576cafef1},
		{"byte_0x0d", string([]byte{0x0d}), 0x0000000000000000, 0xe8d3b882671125a6},
		{"byte_0x0e", string([]byte{0x0e}), 0x0000000000000000, 0x6c2ec20395e1f5ae},
		{"byte_0x0f", string([]byte{0x0f}), 0x0000000000000000, 0xdef0f883f7c4e3fc},
		{"three", "abc", 0x0000000000000000, 0xcb475beafa9c0da2},
		{"four", "abcd", 0x0000000000000000, 0xf8f44f4a65e26132},
		{"seven", "abcdefg", 0x0000000000000000, 0x2760e84111b29a0d},
		{"eight", "abcdefgh", 0x0000000000000000, 0xab159e602a29f41f},
		{"nine", "abcdefghi", 0x0000000000000000, 0x70a51746ca96c1c6},
		{"fifteen", "abcdefghijklmno", 0x0000000000000000, 0x54c03d9b150448c0},
		{"sixteen", "abcdefghijklmnop", 0x0000000000000000, 0xc78ae6a1774adb1e},
		{"seventeen", "abcdefghijklmnopq", 0x0000000000000000, 0x00c427c11a4463b8},
		{"thirty_one", "abcdefghijklmnopqrstuvwxyz01234", 0x0000000000000000, 0xc55d873e50f9b659},
		{"thirty_two", "abcdefghijklmnopqrstuvwxyz012345", 0x0000000000000000, 0x7f6145bd11a4bfc6},
		{"thirty_three", "abcdefghijklmnopqrstuvwxyz0123456", 0x0000000000000000, 0x7fc4dbe9f5cb6d39},
		{"sixty_three", "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVW", 0x0000000000000000, 0x34e7bdf250373022},
		{"sixty_four", "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVW", 0x0000000000000000, 0x34e7bdf250373022},
		{"sixty_five", "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWX", 0x0000000000000000, 0x3722379e2408c3a9},
		{"one_twenty_seven", "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ01", 0x0000000000000000, 0xea2f827bc6979118},
		{"one_hundred", "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.", 0x0000000000000000, 0x1efe5f20ff26d238},
		{"one_hundred_seed", "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.", 0x1234567890abcdef, 0x79a19e37d1a9d56d},
		{"one_twelve", repeat(112), 0x0000000000000000, 0x2061fbc0d6447d23},
		{"one_thirteen", repeat(113), 0x0000000000000000, 0x770cfa17bfe7948b},
		{"two_hundred", repeat(200), 0x0000000000000000, 0x5f6aed2c854aa949},
		{"two_hundred_fifty", repeat(250), 0x0000000000000000, 0x16e63f7afe945d25},
		{"three_hundred", repeat(300), 0x0000000000000000, 0x7ec416e82f693591},
		{"three_hundred_seed", repeat(300), 0xdeadbeefcafebabe, 0xe938192dbcf9495c},
		{"two_kb", repeat(2048), 0x0000000000000000, 0xb563c676422ff0c7},
		{"two_kb_seed", repeat(2048), 0x9e3779b97f4a7c15, 0x3dc49b1d1faf5c5d},
	}

	for _, v := range vectors {
		var got uint64
		if v.seed == 0 {
			got = rapidhash.Hash([]byte(v.data))
		} else {
			got = rapidhash.HashWithSeed([]byte(v.data), v.seed)
		}
		if got != v.want {
			t.Errorf("rapidhash[%q] len=%d seed=%#016x = %#016x, want %#016x", v.label, len(v.data), v.seed, got, v.want)
		}
	}
}

// TestRapidhashDeterministic confirms identical inputs yield identical outputs.
func TestRapidhashDeterministic(t *testing.T) {
	inputs := [][]byte{
		[]byte("test"),
		[]byte{0xDE, 0xAD, 0xBE, 0xEF},
		[]byte("The quick brown fox jumps over the lazy dog"),
		make([]byte, 100),
	}
	for _, in := range inputs {
		if h1, h2 := rapidhash.Hash(in), rapidhash.Hash(in); h1 != h2 {
			t.Errorf("non-deterministic hash for %x", in)
		}
	}
}

// TestRapidhashAvalanche confirms a one-bit change flips many output bits.
func TestRapidhashAvalanche(t *testing.T) {
	a := []byte("test")
	b := []byte("test")
	b[0] ^= 0x01
	h1, h2 := rapidhash.Hash(a), rapidhash.Hash(b)
	if h1 == h2 {
		t.Fatal("hash did not change on one-bit input difference")
	}
	diff := h1 ^ h2
	bits := 0
	for diff != 0 {
		bits++
		diff &= diff - 1
	}
	if bits < 20 {
		t.Errorf("avalanche too weak: only %d bits flipped", bits)
	}
}
